### ISSUE TITLE
Security Exception when sending sms using cordova in android 7.0

### ISSUE THREAD

**Issue by nidhinkumar06** [cordova-sms/cordova-sms-plugin#141]
I am trying to send sms from a device using sms manager by adding the corodova send sms plugin .This app works fine till android6.0 device it sends the sms also but when i tried to send sms from android7.0 it shows me the following security exception.Before sending sms it asks for the permission and i have given the permission also.

Exception:

java.lang.SecurityException: 
at android.os.Parcel.readException(Parcel.java:1683)
at android.os.Parcel.readException(Parcel.java:1636)
at com.android.internal.telephony.IPhoneSubInfo$Stub$Proxy.getGroupIdLevel1(IPhoneSubInfo.java:583)
at android.telephony.TelephonyManager.getGroupIdLevel1(TelephonyManager.java:2163)
at android.telephony.SmsMessage.hasEmsSupport(SmsMessage.java:854)
at com.android.internal.telephony.SmsMessageBase.calcUnicodeEncodingDetails(SmsMessageBase.java:409)
at com.android.internal.telephony.gsm.SmsMessage.calculateLength(SmsMessage.java:796)
at android.telephony.SmsMessage.fragmentText(SmsMessage.java:354)
at android.telephony.SmsManager.divideMessage(SmsManager.java:450)
at com.cordova.plugins.sms.Sms.send(Sms.java:143)
at com.cordova.plugins.sms.Sms.access$400(Sms.java:22)
at com.cordova.plugins.sms.Sms$1.run(Sms.java:102)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)

**Comment by dbaq** [comment]
hey @nidhinkumar06, are sure you are using the latest version?

`at com.cordova.plugins.sms.Sms.send(Sms.java:143)`
this line seems odd to me. https://github.com/cordova-sms/cordova-sms-plugin/blob/master/src/android/Sms.java#L143

**Comment by nidhinkumar06** [comment]
Hi,
  When the sms data contains a single string only of type text it is
working in android7.0 but when it has numbers inside the sms data it gets
crashed and that to only for android 7.0

**Comment by dbaq** [comment]
hey @nidhinkumar06,

can you please share an example? I was not able to reproduce. Thanks

**Comment by dbaq** [comment]
Closing this one since no answer, please feel free to reopen it if it is still happening.
