### ISSUE TITLE
ionic 3 sms.send crashes

### ISSUE THREAD

**Issue by weldermarcosxd** [cordova-sms/cordova-sms-plugin#150]
this code 

`this.sms.send(string, number)
        .then(res => {
          console.log(res);
        })
        .catch(err => {
          console.log(err);
        });`

results in this stacktrace:

`10-13 15:12:12.553 14345-14401/io.ionic.starter E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
                                                                  Process: io.ionic.starter, PID: 14345
                                                                  java.lang.NullPointerException: Attempt to get length of null array
                                                                      at android.os.Parcel.readException(Parcel.java:1626)
                                                                      at android.os.Parcel.readException(Parcel.java:1573)
                                                                      at com.android.internal.telephony.ISms$Stub$Proxy.sendTextForSubscriber(ISms.java:842)
                                                                      at android.telephony.SmsManager.sendTextMessageInternal(SmsManager.java:311)
                                                                      at android.telephony.SmsManager.sendTextMessage(SmsManager.java:294)
                                                                      at com.cordova.plugins.sms.Sms.send(Sms.java:192)
                                                                      at com.cordova.plugins.sms.Sms.access$400(Sms.java:22)
                                                                      at com.cordova.plugins.sms.Sms$1.run(Sms.java:102)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)`

App crashes without even get in the catch block

**Comment by weldermarcosxd** [comment]
this.sms.send(string, number) should be this.sms.send(number, string)

**Comment by Lahrachtdi** [comment]
I'm having the same error
