### ISSUE TITLE
Compile error on Android 

### ISSUE THREAD

**Issue by rolinger** [cordova-sms/cordova-sms-plugin#73]
I did a clean testApp install...loaded the android platform and then added the cordova-plugin-sms as the FIRST plugin and compiled...and it errored out immediately with the same errors as before.  The conflict must be with some android platform code.  

**"Could you please run the exact commands I wrote in my previous comment?** : I did

What component versions are you using?
ionic : v1.5.0
cordova: v5.0.0
npm: v2.7.4
node: v0.12.2
Android Studio: v1.2 Build 141.1890965
Android SDK Platform: v22 with SDK Build Tools v 19.1 thru 23.0.1

Android API 23 (6.0) is not installed.

Below is the entire build process:

```
==================================================

**C:\Users\RPO\dev>ionic start testApp tabs**
Creating Ionic app in folder C:\Users\RPO\dev\testApp based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Updated the hooks directory to have execute permissions
Update Config.xml
Initializing cordova project

Your Ionic project is ready to go! Some quick tips:

 * cd into your project: $ cd testApp

 * Setup this project to use Sass: ionic setup sass

 * Develop in the browser with live reload: ionic serve

 * Add a platform (ios or Android): ionic platform add ios [android]
   Note: iOS development requires OS X currently
   See the Android Platform Guide for full Android installation instructions:
   https://cordova.apache.org/docs/en/edge/guide_platforms_android_index.md.html

 * Build your app: ionic build <PLATFORM>

 * Simulate your app: ionic emulate <PLATFORM>

 * Run your app on a device: ionic run <PLATFORM>

 * Package an app using Ionic package service: ionic package <MODE> <PLATFORM>

For more help use ionic --help or ionic docs

Visit the Ionic docs: http://ionicframework.com/docs


New! Add push notifications to your Ionic app with Ionic Push (alpha)!
https://apps.ionic.io/signup
+---------------------------------------------------------+
+ New Ionic Updates for March 2016
+
+ The View App just landed. Preview your apps on any device
+ http://view.ionic.io
+
+ Invite anyone to preview and test your app
+ ionic share EMAIL
+
+ Generate splash screens and icons with ionic resource
+ http://ionicframework.com/blog/automating-icons-and-splash-screens/
+
+---------------------------------------------------------+

**C:\Users\RPO\dev>cd testApp**

**C:\Users\RPO\dev\testApp>npm install -g gulp**
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.
0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.
0 as soon as possible.
C:\Users\RPO\AppData\Roaming\npm\gulp -> C:\Users\RPO\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js
gulp@3.9.1 C:\Users\RPO\AppData\Roaming\npm\node_modules\gulp
├── pretty-hrtime@1.0.2
├── interpret@1.0.0
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── tildify@1.1.2 (os-homedir@1.0.1)
├── v8flags@2.0.11 (user-home@1.1.1)
├── semver@4.3.6
├── chalk@1.1.1 (escape-string-regexp@1.0.5, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0, ansi-styles@2.2.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.2.0 (rechoir@0.6.2, extend@2.0.1, flagged-respawn@0.3.1, resolve@1.1.7, findup-sync@0.3.0)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, strip-bom@1.0.0, vinyl@0.4.6, defaults@1.0.3, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob
-watcher@0.0.6)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, beeper@1.1.0, lodash._reevaluate@3.0.0, lodash._reinterpo
late@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, vinyl@0.5.3, gulplog@1.0.0, lodash.template@3.6.2, m
ultipipe@0.1.2, through2@2.0.1, dateformat@1.0.12)

**C:\Users\RPO\dev\testApp>npm install gulp --save-dev**
npm WARN package.json testapp@1.1.1 No repository field.
npm WARN package.json testapp@1.1.1 No README data
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.
0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.
0 as soon as possible.
gulp@3.9.1 node_modules\gulp
├── interpret@1.0.0
├── pretty-hrtime@1.0.2
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── tildify@1.1.2 (os-homedir@1.0.1)
├── v8flags@2.0.11 (user-home@1.1.1)
├── semver@4.3.6
├── chalk@1.1.1 (escape-string-regexp@1.0.5, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0, ansi-styles@2.2.0)
├── orchestrator@0.3.7 (sequencify@0.0.7, stream-consume@0.1.0, end-of-stream@0.1.5)
├── liftoff@2.2.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, findup-sync@0.3.0, resolve@1.1.7)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, strip-bom@1.0.0, vinyl@0.4.6, defaults@1.0.3, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob
-watcher@0.0.6)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, be
eper@1.1.0, object-assign@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, gulplog@1.0.0, vinyl@0.5.3, lodash.template@3.6.2, t
hrough2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)

**C:\Users\RPO\dev\testApp>cordova plugin**
com.ionic.keyboard 1.0.4 "Keyboard"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-splashscreen 3.2.0 "Splashscreen"
cordova-plugin-whitelist 1.2.1 "Whitelist"

**C:\Users\RPO\dev\testApp>cordova platform add android**
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.ionicframework.testapp120680
        Name: testApp
        Activity: MainActivity
        Android target: android-22
Copying template files...
Android project created with cordova-android@4.0.0
Running command: "C:\Program Files\nodejs\node.exe" C:\Users\RPO\dev\testApp\hooks\after_prepare\010_add_platform_class.js C:\Users\RPO\dev\
testApp
add to body class: platform-android
Installing "com.ionic.keyboard" for android
Installing "cordova-plugin-console" for android
Installing "cordova-plugin-device" for android
Installing "cordova-plugin-splashscreen" for android
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you
 do *not* need this plugin since the whitelist will be built in.


**C:\Users\RPO\dev\testApp>cordova plugin add cordova-plugin-sim**
Fetching plugin "cordova-plugin-sim" via npm
npm http GET https://registry.npmjs.org/cordova-plugin-sim
npm http 304 https://registry.npmjs.org/cordova-plugin-sim
Installing "cordova-plugin-sim" for android

**C:\Users\RPO\dev\testApp>ionic build android**
Updated the hooks directory to have execute permissions
Running command: "C:\Program Files\nodejs\node.exe" C:\Users\RPO\dev\testApp\hooks\after_prepare\010_add_platform_class.js C:\Users\RPO\dev\
testApp
add to body class: platform-android
Running command: C:\Users\RPO\dev\testApp\platforms\android\cordova\build.bat
ANDROID_HOME=C:\Users\RPO\AppData\Local\Android\sdk
JAVA_HOME=C:\program files\java\jdk1.8.0_40
Running: C:\Users\RPO\dev\testApp\platforms\android\gradlew cdvBuildDebug -b C:\Users\RPO\dev\testApp\platforms\android\build.gradle -Dorg.g
radle.daemon=true
:preBuild
:compileDebugNdk
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar
:CordovaLib:compileDebugNdk
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug
:prepareAndroidCordovaLibUnspecifiedDebugLibrary
:preReleaseBuild
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar
:CordovaLib:compileReleaseNdk
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportV42211Library
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJavaC:\Users\RPO\dev\testApp\platforms\android\src\com\pbakondy\Sim.java:134: error: cannot find symbol
      ContextCompat.checkSelfPermission(this.cordova.getActivity(), type));
                   ^
  symbol:   method checkSelfPermission(Activity,String)
  location: class ContextCompat
C:\Users\RPO\dev\testApp\platforms\android\src\com\pbakondy\Sim.java:139: error: cannot find symbol
      ActivityCompat.requestPermissions(this.cordova.getActivity(), new String[]{type}, 12345);
                    ^
  symbol:   method requestPermissions(Activity,String[],int)
  location: class ActivityCompat
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.959 secs

C:\Users\RPO\dev\testApp\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "C:\Users\RPO\dev\testApp\platforms\android\gradlew cdvBuildDebug -b C:\Users\RPO\dev\testApp
\platforms\android\build.gradle -Dorg.gradle.daemon=true"
ERROR building one of the platforms: Error: C:\Users\RPO\dev\testApp\platforms\android\cordova\build.bat: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: C:\Users\RPO\dev\testApp\platforms\android\cordova\build.bat: Command failed with exit code 1
    at ChildProcess.whenDone (C:\Users\RPO\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:131:2
3)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

**Comment by dbaq** [comment]
Hey,

from what I can see it looks like the problem comes from this plugin https://github.com/pbakondy/cordova-plugin-sim 

```
:compileDebugJavaC:\Users\RPO\dev\testApp\platforms\android\src\com\pbakondy\Sim.java:134: error: cannot find symbol
      ContextCompat.checkSelfPermission(this.cordova.getActivity(), type));
```

Can you test without this plugin?

**Comment by rolinger** [comment]
Ack, think iposted this to the wrong plugin.  Grrrr...

Sent from my mobile device.

From: Didier Baquier

Sent: Thursday, March 10, 12:18 PM

Subject: Re: [cordova-sms-plugin] Compile error on Android  (#73)

To: cordova-sms/cordova-sms-plugin

Cc: rolinger

Hey,

from what I can see it looks like the problem comes from this plugin https://github.com/pbakondy/cordova-plugin-sim 

:compileDebugJavaC:\Users\RPO\dev\testApp\platforms\android\src\com\pbakondy\Sim.java:134: error: cannot find symbol ContextCompat.checkSelfPermission(this.cordova.getActivity(), type)); 

Can you test without this plugin?

**Comment by dbaq** [comment]
That happens :)

Closing this ticket.
